name: geohash
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0

  #text
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  flutter_typeahead: ^5.2.0

  #map
  flutter_map: ^6.1.0
  dart_geohash: ^2.1.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^8.0.8


  #utils
  fluttertoast: ^8.2.5


  #firebase
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3

  #images
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  #statemanagement
  flutter_riverpod: ^2.5.1

  #color
  flutter_hsvcolor_picker: ^1.5.0

  #adaptive
  flutter_platform_widgets: ^7.0.0
  flutter_screenutil: ^5.9.0

  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
